### ISSUE TITLE
Change of dates make line data disappear  

### ISSUE THREAD

**Issue by yael-naor** [hasadna/open-bus-map-search#538] opened 2024-02-26 19:15 UTC
On the page "אחוזי יציאה מכלל הנסיעות":
I'm requesting information on route 24 from Metropolin company. 
When I request dates 5/2/24 until 25/2/24, I receive valid information
However, when I request dates 4/2/24 until 25/2/24, I receive a message that there's not such line.
F12 shows that the data exists for the latter dates as well.

**Comment by InbarSle** [comment] 2024-03-11 16:26
Can i be assigned to this?

**Comment by shootermv** [comment] 2024-03-12 10:38
Of course you can!

**Comment by YuvalMasada** [comment] 2024-03-21 14:57
Hi @yael-naor ,
Can you reproduce this issue every time you play with the dates?

**Comment by itsoriki** [comment] 2024-05-05 15:19
@NoamGaash I can't reproduce the issue - it might be irrelevant now

**Comment by NoamGaash** [comment] 2024-05-05 16:37
@itsoriki did you try the right page and settings?
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/5e8388d1-d97d-467b-94f8-ceacce60a208)
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/04d7da4f-3115-4d4d-9f60-4fe9973d9c8f)

**Comment by itsoriki** [comment] 2024-05-08 09:01
@NoamGaash After a serious investigation I have come up with the following: 
The problem is in the [gtfsService](https://github.com/hasadna/open-bus-map-search/blob/main/src/api/gtfsService.ts)
There are some issues I found there:
- In line 32 there is a filter of the `gtfsRoutes` with an interesting condition (see picture)
![image](https://github.com/hasadna/open-bus-map-search/assets/93577239/a43c5c84-07e0-4269-9432-403c60578bf0)
This filter removes all the routes except for the ones with the date of the `to` parameter - meaning the routes in the last day of the search range (In our example the search range is from 5/2/24 to 25/2/24, so the filter will result only the routes of the 25th). Now, when we extend the search range to be from the 4/2/24, there are more than 100 routes the gtfs finds, but the limit is only 100 (see picture) 
![image](https://github.com/hasadna/open-bus-map-search/assets/93577239/8bad9664-15f6-4799-a3d6-4429f1faa1c5)
So we end up getting just the first 100 with the routes of the final day (25th) being left out of the array - and then when the filter does its thing - all the routes get filtered out and the result in the UI is "הקו לא נמצא".
Btw, even when we search from **5/2/24** and the UI shows some results - they are not the "whole story" and some routes are left out (2 to be precise) because of the `limit: 100`.
Now, I saw that this filter is meant to solve another problem mentioned in #244 - so we need to figure out a better way to do things here.
- The limit of the gtfsRoutes query is `100` but there are more than 100 in our case for example - and the ones that left out (the ones of the 25/2/24) are apparently the important ones (I assume they are important because we filter for them and only them in the code as seen above)  
- The GTFS API returns also the routes of the day before the from day (In our example when we search for 5/2/24 - 25/2/24, the api gives us also the routes of the 4/2/24 - which is the one day over what we asked for. I saw that @ArkadiK94 referred to this in his #244 PR as "the routes of yesterday problem" - so I guess you are aware of the issue


### Conclusion
We parse the routes from the GTFS API in a way that might and actually leads to problems - Let's discuss also changes in the backend to address the problem as a whole!

**Comment by NoamGaash** [comment] 2024-05-08 13:43
@ShayAdler You got to see this :exploding_head: 
@itsoriki Thank you! That's an amazing investigation :clap: 
seems like this method assumes that the `fromTimestamp` and `toTimestamp` belong to the same date, which is obviously wrong in our case.
maybe we should change to:
```js
    .filter((route) => route.date.getDate() <= toTimestamp.date() && route.date.getDate() >= fromTimestamp.date())
```
or something similar (?)

**Comment by itsoriki** [comment] 2024-05-08 14:25
That's exactly what I had in mind! I'll fix it right away :)

**Closed** 2024-05-09 06:40 UTC
Labels: good first issue, frontend
